language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: app-pruebas-curso-github
  on: master
  skip_cleanup: true
  api_key:
    secure: XG3bOkADCEWj+VweZksOkrCKVfMo1NiCBjHqG3RAZhzT5yvEdz8Y0VgT/iSjlwDVJnzeEV7NMGDpIJgJBgvelpgTKEUAv/Nh92XqvyzRYquMD2EL1shW6tK5XwzH8T7JyJ0d41GRqoiNz3liPlLO+6fVloVL7laUjLLjSSmSsv1opMJdbmH2nmJQDm1gleEoRaiun1pv5qdeBZTIl9cLi7fYI0cKOo+x10SqM4mEmfrgMPY9tEl6ffobOKV7OJwA35ObchXa+muE4zML47avPwzXkZRbAlRyzIT9LvhCWNYTv9ecwrHvbR4hqkfjkVAgDLFURo1ycYI+KZsl+o0vYp4l67RNJ6AxVF41/G6RO9MSVtD37yj1iRsXcb0RJgmgEcQM7mZEJPWwuBuXDKIfRorlJYQscsVyPz+pFcFZDU1DkUVEEzkqqHF5a8wCesJWsK5J2dpLJTX92yK4eh5+LcpTXO+F6+Ne+f84G+J/daiIYyQfOmsRCUsN+iqhhHiYqJx7oZTAYbO+r+E3ioQUYc4mU+QEIl7rNhUPqydX0cflck32ze5qWHGphM18dW0u7XYTjQyqbbWqX/dxtnc9Gh+AEiWYqQkSdNdbDVOdMbXCDlB3HRDgrxVK+D2Ka0SUNrYs55tPiB5vkdQpawwc/R4HtPk9RJ3ulTCCFC8G16s=
